apiVersion: v1  
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-role
  namespace: default
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelines", "tasks", "taskruns"]
  verbs: ["get","list","create","watch"]
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims", "secrets", "configmaps"]
  verbs: ["get","list","create","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sa
  namespace: default
roleRef:
  kind: Role
  name: tekton-triggers-role
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for accessing ClusterTasks and Tekton Triggers
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-clusterrole
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["clustertasks", "tasks"]
    verbs: ["get", "list"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clustertriggerbindings", "eventlisteners", "triggers", "triggerbindings", "triggertemplates", "interceptors", "clusterinterceptors"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-clusterrole