

services:
  my-node-app:
    image: my-node-app
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/admin
    depends_on:
      - mongo
    develop:
      watch:
        - path: .
          target: /usr/src/app
          action: sync

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ME_CONFIG_MONGODB_ADMINUSERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: ME_CONFIG_MONGODB_ADMINPASSWORD
      ME_CONFIG_MONGODB_URL: ME_CONFIG_MONGODB_URL
      ME_CONFIG_BASICAUTH: ME_CONFIG_BASICAUTH

volumes:
  mongo-data:
   
      