apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo/deployment.yaml
  - mongo/service.yaml
  - mongo/pvc.yaml
  - mongo-express/deployment.yaml
  - mongo-express/service.yaml
  - node-app/deployment.yaml
  - node-app/service.yaml

images:
  - name: muretimiriti/test1            # ← Matches image name in deployment.yaml
    newName: muretimiriti/test1   # ← Docker Hub repo
    newTag: latest                # ← Overridden by ArgoCD at deploy time
