apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)

    - name: image-reference
      value: muretimiriti/test1:$(body.after)

    # Optional: set to "true" to enable SonarQube scan in the pipeline.
    - name: run-sonarqube
      value: "false"
